// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vzkeombjsotsragrccqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a2VvbWJqc290c3JhZ3JjY3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjAxMjAsImV4cCI6MjA3MTE5NjEyMH0.6EeBuvsi-qSectrGF66MupZYKJSUEC7okKpN5uzqelg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});